// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/predict-failure.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float32                `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ResponseLatencyMs int32                  `protobuf:"varint,3,opt,name=response_latency_ms,json=responseLatencyMs,proto3" json:"response_latency_ms,omitempty"`
	ErrorsLastMinute  int32                  `protobuf:"varint,4,opt,name=errors_last_minute,json=errorsLastMinute,proto3" json:"errors_last_minute,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_predict_failure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_predict_failure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_predict_failure_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *PredictRequest) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *PredictRequest) GetResponseLatencyMs() int32 {
	if x != nil {
		return x.ResponseLatencyMs
	}
	return 0
}

func (x *PredictRequest) GetErrorsLastMinute() int32 {
	if x != nil {
		return x.ErrorsLastMinute
	}
	return 0
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    string                 `protobuf:"bytes,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_predict_failure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_predict_failure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_predict_failure_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPrediction() string {
	if x != nil {
		return x.Prediction
	}
	return ""
}

func (x *PredictResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_predict_failure_proto protoreflect.FileDescriptor

const file_proto_predict_failure_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/predict-failure.proto\x12\x05proto\"\xae\x01\n" +
	"\x0ePredictRequest\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12.\n" +
	"\x13response_latency_ms\x18\x03 \x01(\x05R\x11responseLatencyMs\x12,\n" +
	"\x12errors_last_minute\x18\x04 \x01(\x05R\x10errorsLastMinute\"o\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\tR\n" +
	"prediction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2X\n" +
	"\x15PredictFailureService\x12?\n" +
	"\x0ePredictFailure\x12\x15.proto.PredictRequest\x1a\x16.proto.PredictResponseB/Z-github.com/AnitsuriW/ollama-healthcheck/protob\x06proto3"

var (
	file_proto_predict_failure_proto_rawDescOnce sync.Once
	file_proto_predict_failure_proto_rawDescData []byte
)

func file_proto_predict_failure_proto_rawDescGZIP() []byte {
	file_proto_predict_failure_proto_rawDescOnce.Do(func() {
		file_proto_predict_failure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_predict_failure_proto_rawDesc), len(file_proto_predict_failure_proto_rawDesc)))
	})
	return file_proto_predict_failure_proto_rawDescData
}

var file_proto_predict_failure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_predict_failure_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: proto.PredictRequest
	(*PredictResponse)(nil), // 1: proto.PredictResponse
}
var file_proto_predict_failure_proto_depIdxs = []int32{
	0, // 0: proto.PredictFailureService.PredictFailure:input_type -> proto.PredictRequest
	1, // 1: proto.PredictFailureService.PredictFailure:output_type -> proto.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_predict_failure_proto_init() }
func file_proto_predict_failure_proto_init() {
	if File_proto_predict_failure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_predict_failure_proto_rawDesc), len(file_proto_predict_failure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_predict_failure_proto_goTypes,
		DependencyIndexes: file_proto_predict_failure_proto_depIdxs,
		MessageInfos:      file_proto_predict_failure_proto_msgTypes,
	}.Build()
	File_proto_predict_failure_proto = out.File
	file_proto_predict_failure_proto_goTypes = nil
	file_proto_predict_failure_proto_depIdxs = nil
}
